name: wander2
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^0.1.3
  camera: ^0.5.8+7
  path_provider: ^1.6.22
  path: ^1.7.0
  tflite: ^1.1.1
  image_picker: ^0.6.7
  firebase_core: 0.5.1
  firebase_auth: 0.18.2
  cloud_firestore: 0.14.0
  modal_progress_hud: ^0.1.3
  flutter_swiper: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/wanderer.png
    - assets/labelmap.txt
    - assets/ssd_mobilenet.tflite
    - assets/Workers_label_map.pbtxt
    - assets/temple_label_map.txt
    - assets/last_hope.pbtxt
    - assets/landmark_label_map.pbtxt
    - assets/landmark_object_detection_model.tflite
    - assets/landmark_object_detection_model_0.5.tflite
    - assets/model.tflite
    - assets/model2.tflite
  fonts:
    - family: Flavors
      fonts:
        - asset: fonts/Flavors-Regular.ttf
